### ISSUE TITLE
Using this with Tags

### ISSUE THREAD

**Issue by milosmns** [night-codes/mgo-ai#1]
Hi, any ideas on how to use this from tags somehow? I have a User class which has all of its properties annotated with `bson` tags, so I don't really have to use `bson.M` or `bson.D` or whatever. I just push the object as an interface and it works.
So I'd like to use your approach for the objects that I have and not have to wrap them in a `bson.M` interface to be able to auto-increment.

**Comment by night-codes** [comment]
Can you give me some sample code?  Do you mean something like that?

```go
user := User{
    ID: ai.Next("users"),
    // .....
}
```

**Comment by milosmns** [comment]
Well yeah, something like this. A example of what I want to do:

```go
type User struct {
  ID       int32   `bson:"user_id"` // <-- I want this to auto-increment somehow
  Username string  `bson:"user_username"`
  FullName string  `bson:"user_full_name"`
  Email    *string `bson:"user_email"`
  // etc
}
```

So I very much prefer to use tags because shooting a `User` instance at Mongo just works.

**Comment by night-codes** [comment]
What prevents to set the value of the struct field before sending it to mongo Insert? In any case, you'll have to call one of the ai methods before Insert. 
```go
user := User{/* ... */}

// 1
user.ID = ai.Next("users")
db.C("users").Insert(user)

// 2
ai.IncByTag(&user)
db.C("users").Insert(user)
```

Writing the second method is not difficult, but using `reflect` to read tags will definitely slow down the program and will not bring significant benefits, it seems to me.

**Comment by milosmns** [comment]
Hmm ok yeah you're right.

Thanks for the help!
